// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-EEk3Yzap4oyQHGAOy_wNAn7HsoEX18U',
    appId: '1:818947733601:web:875b5a6292df7ae42c1220',
    messagingSenderId: '818947733601',
    projectId: 'saferide-iot-app-c9d8f',
    authDomain: 'saferide-iot-app-c9d8f.firebaseapp.com',
    storageBucket: 'saferide-iot-app-c9d8f.firebasestorage.app',
    measurementId: 'G-GWFZR8CZ8P',
    databaseURL:
        'https://saferide-iot-app-c9d8f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3GF5SQt9tE7rQt2pqRy5xZj1AGJljyY',
    appId: '1:818947733601:ios:9809d5fe87b840942c1220',
    messagingSenderId: '818947733601',
    projectId: 'saferide-iot-app-c9d8f',
    storageBucket: 'saferide-iot-app-c9d8f.firebasestorage.app',
    iosBundleId: 'com.example.saferideIotApp',
    databaseURL:
        'https://saferide-iot-app-c9d8f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3GF5SQt9tE7rQt2pqRy5xZj1AGJljyY',
    appId: '1:818947733601:ios:9809d5fe87b840942c1220',
    messagingSenderId: '818947733601',
    projectId: 'saferide-iot-app-c9d8f',
    storageBucket: 'saferide-iot-app-c9d8f.firebasestorage.app',
    iosBundleId: 'com.example.saferideIotApp',
    databaseURL:
        'https://saferide-iot-app-c9d8f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4cQqLjTcuIi5LqoU1cfhl5IlXgVvyJs',
    appId: '1:818947733601:android:6023b88732701ba32c1220',
    messagingSenderId: '818947733601',
    projectId: 'saferide-iot-app-c9d8f',
    storageBucket: 'saferide-iot-app-c9d8f.firebasestorage.app',
    databaseURL:
        'https://saferide-iot-app-c9d8f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-EEk3Yzap4oyQHGAOy_wNAn7HsoEX18U',
    appId: '1:818947733601:web:5916b5fa908dcd6a2c1220',
    messagingSenderId: '818947733601',
    projectId: 'saferide-iot-app-c9d8f',
    authDomain: 'saferide-iot-app-c9d8f.firebaseapp.com',
    storageBucket: 'saferide-iot-app-c9d8f.firebasestorage.app',
    measurementId: 'G-0M5S9EWKQ3',
    databaseURL:
        'https://saferide-iot-app-c9d8f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
