import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'screens/splash_screen.dart';
import 'firebase_options.dart'; // This file will be generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await dotenv.load();

  // NOTE: You must run 'flutterfire configure' to generate firebase_options.dart
  // For now, we wrap in a try-catch to allow the UI to run even if not configured yet (for demo/check)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase not initialized: $e");
    // In a real app, you might show an error screen or use a mock service
  }

  runApp(const SafeRideApp());
}

class SafeRideApp extends StatelessWidget {
  const SafeRideApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SafeRide',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Segoe UI', // Clean font
        primaryColor: const Color(0xFF0056D2),
        scaffoldBackgroundColor: Colors.white,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF0056D2)),
        useMaterial3: true,
      ),
      home: const SplashScreen(),
    );
  }
}
